fix `gc_object_moved_p` - it was renamed to `rb_gc_impl_object_moved_p`
```
gc.c:3131:9: error: call to undeclared function 'gc_object_moved_p'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        UPDATE_IF_MOVED(objspace, RARRAY(v)->as.heap.aux.shared_root);
        ^
gc.c:465:44: note: expanded from macro 'UPDATE_IF_MOVED'
                                           ^
gc.c:453:16: note: expanded from macro 'TYPED_UPDATE_IF_MOVED'
    } else if (gc_object_moved_p((_objspace), (VALUE)(_thing))) {    \
               ^
```