Do not hide the IO in rb_f_backquote if a scheduler is registered
[Bug #19624]

Otherwise we end up passing an hidden object to Ruby code
which is invalid.

```
NotImplementedError: method `hash' called on hidden T_FILE object (0x0000000119cd5ca0 flags=0xb)
    src/graphql-ruby/spec/support/dummy_scheduler.rb:159:in `io_wait'
```