Support Pathnames in Net::FTP by making String conversion explicit.
Pathname support was added to list and getbinaryfile in 613a324f.

Fixes the following error when calling String#+ with a Pathname:
  TypeError: no implicit conversion of Pathname into String

Found in the following Net::FTP instance methods:
chdir
delete
gettextfile
mdtm
mkdir
nlst
putbinaryfile
puttextfile
rename
rmdir
size