[flori/json] tests/ractor_test.rb: make assert_separately available
Require tests/lib/helper.rb to avoid:

NoMethodError: undefined method `assert_separately'

https://github.com/flori/json/commit/a81bcc0328