ruby: fix test failures
* test_exlibs.rb add require 'test/unit' for fix below error

test_extlibs.rb:6:in `<main>': uninitialized constant Test (NameError)

* other nine test_*.rb add require 'minitest/autorun' to fix below errors

1.Error: test_error_handling(TestCMath):
NoMethodError: undefined method `assert_raise_with_message' for #TestCMath:0x000056300b0c5800
Did you mean? assert_raise_message

2.test_cmath.rb:31:in `test_log'
Error: test_log(TestCMath): RangeError: can't convert 0.8047189562170503+1.1071487177940904i into Float

This commit is for fix issue: https://bugs.ruby-lang.org/issues/15746?next_issue_id=15745

Signed-off-by: Changqing Li <changqing.li@windriver.com>