Assume pch is stabler than pdb
to fix random AppVeyor failures like:
https://ci.appveyor.com/project/ruby/ruby/builds/32159878/job/l2p38snw8yxxpp8h

C:\Users\appveyor\AppData\Local\Temp\1/_ruby_mjit_p27500u0.c(1) : error C2859:
c:\projects\ruby\x64-mswin_120\include\ruby-2.8.0\x64-mswin64_120\rb_mjit_header-2.8.0.pdb
is not the pdb file that was used when this precompiled header was created, recreate the precompiled header.

Currently ifchange skips updating .time and .pch when there's no change
in .pch, but it does not skip updating .pdb. I suspect it causes
mismatch between .pdb and .pch. Assuming .pch is stabler (i.e. When .pdb
has no change, .pch never has any change either), I hope this will work
as a workaround until we support updating multiple files in ifchange.bat.

There's a possibility that .pdb is completely unstable (it never
produces the same binary). In that case please feel free to revert this
commit.