Add diff_text to pretty-print IR differences in unit test failures
This produces errors that look like

    thread 'hir::tests::test_display_types' panicked at src/hir.rs:1777:9:
    assertion `left == right` failed: Differences found (-expected, +actual):
    ---
     bb0():
       v0:NilClassExact = Const Value(nil)
       v2:TrueClassExact = Const Value(true)
       v6:CBool[true] = Test v2
    -  IfFalse v6, bb1(v)
    +  IfFalse v6, bb1(v2)
       v9:Fixnum[3] = Const Value(3)
       Return v9
     bb1(v12):
       v14 = Const Value(4)
       Return v14
    ---

instead of just

    left: "bb0():\n  v0:NilClassExact = Const Value(nil)\n  v2:TrueClassExact = Const Value(true)\n  v6:CBool[true] = Test v2\n  IfFalse v6, bb1(v2)\n  v9:Fixnum[3] = Const Value(3)\n  Return v9\nbb1(v12):\n  v14 = Const Value(4)\n  Return v14\n"
    right: "bb0():\n  v0:NilClassExact = Const Value(nil)\n  v2:TrueClassExact = Const Value(true)\n  v6:CBool[true] = Test v2\n  IfFalse v6, bb1(v)\n  v9:Fixnum[3] = Const Value(3)\n  Return v9\nbb1(v12):\n  v14 = Const Value(4)\n  Return v14\n"