Fix `rb_mmtk_scan_finalizer_tbl_roots` function
1) first change `mark_finalizer_tbl` to `rb_gc_impl_objspace_mark`
2) Correctly get objspace
3) Move function down so it has access to `rb_gc_impl_objspace_mark`.

```
gc_impl.c:5814:5: error: call to undeclared function 'rb_gc_impl_objspace_mark'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    rb_gc_impl_objspace_mark((void *)objspace);
    ^
gc_impl.c:5814:5: note: did you mean 'rb_gc_impl_object_id'?
gc_impl.c:1766:1: note: 'rb_gc_impl_object_id' declared here
rb_gc_impl_object_id(void *objspace_ptr, VALUE obj)
^
gc.c:2519:21: error: use of undeclared identifier 'gc_mark_tbl_no_pin_i'; did you mean 'gc_mark_tbl_no_pin'?
    st_foreach(tbl, gc_mark_tbl_no_pin_i, (st_data_t)objspace);
                    ^~~~~~~~~~~~~~~~~~~~
                    gc_mark_tbl_no_pin
gc.c:2515:1: note: 'gc_mark_tbl_no_pin' declared here
gc_mark_tbl_no_pin(void *objspace, st_table *tbl)
^
1gc_impl.c error: generated10313.
:1: error: conflicting types for 'rb_gc_impl_objspace_mark'
rb_gc_impl_objspace_mark(void *objspace_ptr)
^
gc_impl.c:5814:5: note: previous implicit declaration is here
    rb_gc_impl_objspace_mark((void *)objspace);
    ^
```