Update expoennt to exponent to match member name.
`expoennt` was causing a bigdecimal build to fail with:

    bigdecimal.c: In function âVpSetPTRâ:
    bigdecimal.c:4421:5: error: âRealâ has no member named âexpoenntâ