Revert "Update bundled_gems"
This reverts commit ba72cfa6616d377ceb62d94f10157097349634e5.

https://github.com/ruby/ruby/actions/runs/9396582605/job/25878058017#step:10:788

```
../../../../../../src/.bundle/gems/rbs-3.5.0/ext/rbs_extension/location.h:23:25: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
   23 |   rbs_loc_entry entries[0];
      |                         ^
1 error generated.
```