fix missing `any`
gc.c:2899:69: error: use of undeclared identifier 'any'
            rb_mmtk_scan_offsetted_strbuf_field((char**)&RMATCH_EXT(any)->char_offset, false);

i _think_ `obj` is correct here?