YJIT: Fix crash when yielding keyword args
Code like the following is crashing for us on 3.4.1:

```ruby
def a(&) = yield(x: 0)

1000.times { a { |x:| x } }
```

Crash:

```
ruby: YJIT has panicked. More info to follow...
thread '<unnamed>' panicked at ./yjit/src/codegen.rs:8018:13:
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /Users/nickdower/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:367:5
   4: yjit::codegen::gen_send_iseq
```

The assertion that is failing seems to have been added in #9596. As far
as we can tell, this code:

```rust
// Pop surplus positional arguments when yielding
if arg_setup_block {
    let extras = argc - required_num - opt_num;
    if extras > 0 {
        // Checked earlier. If there are keyword args, then
        // the positional arguments are not at the stack top.
        assert_eq!(0, kw_arg_num);
```

Is referring to this prior check:

```rust
// Bail if we can't drop extra arguments for a yield by just popping them
if supplying_kws && arg_setup_block && argc > (kw_arg_num + required_num + opt_num) {
```

But in one case `kw_arg_num` is being included in the sum, and in the
other it isn't.

We attempted a fix by ignoring `kw_arg_num` in the initial check.

Co-authored-by: Dani Acherkan <dtl.117@gmail.com>