Provisionally ignore panics that happen in these days often [ci skip]
```
    ruby: YJIT has panicked. More info to follow...
  thread '<unnamed>' panicked at src/core.rs:2751:9:
  assertion `left == right` failed: each stub expects a particular iseq
    left: 0x7fc8d8e09850
   right: 0x7fc8d2c2f3a0
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
     2: core::panicking::assert_failed_inner
     3: core::panicking::assert_failed
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:279:5
     4: yjit::core::branch_stub_hit_body
               at /home/runner/work/ruby/ruby/src/yjit/src/core.rs:2751:9
     5: yjit::core::branch_stub_hit::{{closure}}::{{closure}}
               at /home/runner/work/ruby/ruby/src/yjit/src/core.rs:2696:36
     6: yjit::stats::with_compile_time
               at /home/runner/work/ruby/ruby/src/yjit/src/stats.rs:979:15
     7: yjit::core::branch_stub_hit::{{closure}}
               at /home/runner/work/ruby/ruby/src/yjit/src/core.rs:2696:13
     8: std::panicking::try::do_call
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
     9: __rust_try
    10: std::panicking::try
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
    11: std::panic::catch_unwind
               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
    12: yjit::cruby::with_vm_lock
               at /home/runner/work/ruby/ruby/src/yjit/src/cruby.rs:647:21
    13: yjit::core::branch_stub_hit
               at /home/runner/work/ruby/ruby/src/yjit/src/core.rs:2695:9
    14: <unknown>
```