Fix errors when `RDoc::RI::Paths::HOMEDIR` is nil
https://rubyci.org/logs/rubyci.s3.amazonaws.com/scw-ad7f67/ruby-master/log/20200425T175405Z.fail.html.gz
```
  4) Error:
TestRDocServlet#test_asset:
NoMethodError: undefined method `replace' for nil:NilClass
    /home/chkbuild/build/20200425T175405Z/ruby/test/rdoc/test_rdoc_servlet.rb:48:in `setup'

  5) Error:
TestRDocServlet#test_asset:
NoMethodError: undefined method `replace' for nil:NilClass
    /home/chkbuild/build/20200425T175405Z/ruby/test/rdoc/test_rdoc_servlet.rb:63:in `teardown'
```
...
```
 74) Error:
TestRDocServlet#test_store_for_site:
NoMethodError: undefined method `replace' for nil:NilClass
    /home/chkbuild/build/20200425T175405Z/ruby/test/rdoc/test_rdoc_servlet.rb:48:in `setup'

 75) Error:
TestRDocServlet#test_store_for_site:
NoMethodError: undefined method `replace' for nil:NilClass
    /home/chkbuild/build/20200425T175405Z/ruby/test/rdoc/test_rdoc_servlet.rb:63:in `teardown'
```