Add make dependency for main.c on id.h
main.c depends on id.h and id.h is auto-generated, so on a new build there
is a race condition the build fails if main.c is compiled before id.h has
been generated. The error looks like:

      In file included from ./main.c:28:
      In file included from ./internal/gc.h:17:
      ./vm_core.h:117:10: fatal error: 'id.h' file not found
      #include "id.h"
              ^~~~~~