include header to fix missing `rb_gc_mark_global_tbl`
```
gc_impl.c:5823:5: error: call to undeclared function 'rb_gc_mark_global_tbl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    rb_gc_mark_global_tbl();
    ^
```