Skip RBS tests for RDocPluginParserTest caused by interface change of RDoc 6.14.0
https://github.com/ruby/ruby/actions/runs/15199473008/job/42750815986?pr=13421

```
 Error: ArgumentError: wrong number of arguments (given 0, expected 1)
  /Users/runner/work/ruby/ruby/src/lib/rdoc/store.rb:123:in 'initialize'
  /Users/runner/work/ruby/ruby/src/gems/src/rbs/test/rbs/rdoc/rbs_parser_test.rb:8:in 'Class#new'
  /Users/runner/work/ruby/ruby/src/gems/src/rbs/test/rbs/rdoc/rbs_parser_test.rb:8:in 'RDocPluginParserTest#parser'
  /Users/runner/work/ruby/ruby/src/gems/src/rbs/test/rbs/rdoc/rbs_parser_test.rb:147:in 'RDocPluginParserTest#test_instance_method_comment_and_tokens'
```