Remove unused timeout in parsey CI.
This is unset and has no fallback. it's causing an error in the CI
output

Error: An error occurred when attempting to determine the step timeout.
Error: The template is not valid. .github/workflows/parsey.yml (Line:
78, Col: 26): Unexpected value ''