Revert "Enhanced RDoc for Integer (#5099)"
This reverts commit fc456adc6a62d09b755243b8c8f190934b9965d6.

It broke the CI check.

https://github.com/ruby/ruby/runs/4207922247?check_suite_focus=true#step:3:4
```
numeric.c:3518: *     255.chr(Encoding::UTF_8) # => "ÿ"
Error: Process completed with exit code 1.
```