* vm_insnhelper.c (INLINE): disbale r54738 if __NO_INLINE__ is defined.   It caused "undefined reference to `vm_getivar'".
git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@54745 b2dd03c8-39d4-4d8f-98ff-823fe69b080e